### ISSUE TITLE
Please update to Node 20

### ISSUE THREAD

**Issue by langsmith** [ALJAZEERAPLUS/sauce-labs-storage-action#10]
Please update this Action to use Node 20 at https://github.com/ALJAZEERAPLUS/sauce-labs-storage-action/blob/main/action.yml#L44 because of https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

**Comment by vhsantos26** [comment]
Thanks a lot for highlighting it. We will push it in the next release.

**Comment by vhsantos26** [comment]
@langsmith It was resolved on the release [v2.1.0](https://github.com/ALJAZEERAPLUS/sauce-labs-storage-action/releases/tag/v2.1.0)
