### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by david-p8** [ALJAZEERAPLUS/sauce-labs-storage-action#8]
Currently the example for uploading a file is outdated. It says it should send `file-path `when it accepts `upload-file-path`

**Comment by langsmith** [comment]
@david-p8 , did you run into the issue I'm seeing at https://github.com/ALJAZEERAPLUS/sauce-labs-storage-action/issues/9? Do you have a workaround?

**Comment by vhsantos26** [comment]
Thanks a lot for highlighting it. We will push it in the next release.

**Comment by vhsantos26** [comment]
@david-p8  It was resolved on the release [v2.1.0](https://github.com/ALJAZEERAPLUS/sauce-labs-storage-action/releases/tag/v2.1.0)
